classes: Employee.class
Employee.class: Employee.class
	javac -d . jstuff/stuff/Employee.java

executables: EmployeeTest.class
EmployeeTest.class: EmployeeTest.class
	javac -d . tests/EmployeeTest.java

